# Generated by Django 5.0.2 on 2024-02-13 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paragraph_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraph',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
