# Generated by Django 5.0.2 on 2024-02-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paragraph_app', '0002_alter_paragraph_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paragraph',
            name='description',
        ),
        migrations.AddField(
            model_name='paragraph',
            name='email',
            field=models.EmailField(default='new@gmailcom', max_length=50),
        ),
        migrations.AddField(
            model_name='paragraph',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
