# Generated by Django 5.0.2 on 2024-02-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paragraph_app', '0003_remove_paragraph_description_paragraph_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paragraph',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
